# deployments/mongodb-dev.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-primary
  namespace: cptm8-dev
  labels:
    app: mongodb-primary
    environment: development
    tier: data
spec:
  serviceName: mongodb-primary-headless
  replicas: 1  # Start with single node for dev simplicity
  selector:
    matchLabels:
      app: mongodb-primary
      environment: development
  template:
    metadata:
      labels:
        app: mongodb-primary
        environment: development
        tier: data
        mongodb-role: primary
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        command:
        - mongod
        - --replSet
        - rs0
        - --bind_ip_all
        - --port
        - "27017"
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: cptm8-config
              key: MONGO_INITDB_DATABASE
        - name: MONGO_INITDB_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: cptm8-config
              key: MONGO_INITDB_COLLECTION
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: cptm8-config
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongodb-root-password
        - name: MONGO_NON_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: cptm8-config
              key: MONGO_NON_ROOT_USERNAME
        - name: MONGO_NON_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongodb-user-password
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /data/configdb
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30    # Wait before first check
          periodSeconds: 10          # Check every 10 seconds
          timeoutSeconds: 5          # 5 second timeout
          successThreshold: 1        # 1 success to mark healthy
          failureThreshold: 3        # 3 failures before restart
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1        # 1 success to mark ready
          failureThreshold: 3        # 3 failures to mark not ready
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 10001
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: cptm8-dev-ssd-retain
      resources:
        requests:
          storage: 20Gi
  - metadata:
      name: mongodb-config
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: cptm8-dev-ssd-delete
      resources:
        requests:
          storage: 1Gi