# OpenSearch Configuration ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
data:
  internal_users.yml: |
    ---
    _meta:
      type: "internalusers"
      config_version: 2

    admin:
      hash: "$2b$12$wahNgJKUu5516kXevE26CePFXaHP3kNMRvCAIIui3RwOKy1n96sqC"
      reserved: true
      backend_roles:
      - "admin"
      description: "Staging admin user"

    kibanaserver:
      hash: "$2b$12$hZ518tz20e2ZcYjt43Oki.83BJ2eP/F7eIiXniGFUhBCXxjL7XA2q"
      reserved: true
      description: "Staging kibanaserver user"