# External LoadBalancer services for frontend applications
apiVersion: v1
kind: Service
metadata:
  name: dashboardm8-external
  namespace: cptm8-dev
  labels:
    app: dashboardm8
    environment: development
  annotations:
    # AWS LoadBalancer annotations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: dashboardm8
    environment: development
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: socketm8-external
  namespace: cptm8-dev
  labels:
    app: socketm8
    environment: development
  annotations:
    # AWS LoadBalancer annotations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: socketm8
    environment: development
  ports:
    - name: http
      port: 80
      targetPort: 4000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 4000
      protocol: TCP