apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cptm8-dev-ssd-retain
  labels:
    environment: development
    tier: data
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cptm8-dev-ssd-delete
  labels:
    environment: development
    tier: data
provisioner: rancher.io/local-path
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# Storage Class for Shared Log Volumes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cptm8-dev-logs-shared
  labels:
    environment: development
    component: logs
    tier: storage
provisioner: kubernetes.io/no-provisioner
parameters:
  type: local
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - rw
  - relatime
  - uid=10001
  - gid=10001