# secrets-dev.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: cptm8-dev
type: Opaque
data:
  postgresql-root-password: "b64pass"
  postgresql-user-password: "b64pass"
  postgresql-database-url: "b64connectionstring"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: cptm8-dev
type: Opaque
data:
  mongodb-root-password: "b64pass"
  mongodb-user-password: "b64user"
  mongodb-database-url: "b64connectionstring"
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-secrets
  namespace: cptm8-dev
type: Opaque
data:
  opensearch-admin-password: "b64pass"
  # opensearch-kibanaro-password:
  # opensearch-kibanaserver-password:
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: cptm8-dev
type: Opaque
data:
  rabbitmq-url: "b64connectionstring"
  rabbitmq-username: "b64user"
  rabbitmq-password: "b64pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
  namespace: cptm8-dev
type: Opaque
data:
    auth-secret: "b64pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secrets
  namespace: cptm8-dev
type: Opaque
data:
    smtp-username: "b64user"
    smtp-password: "b64pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: cptm8-dev
type: Opaque
data:
    aws-key: "b64key"
    aws-secret: "b64secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: google-secrets
  namespace: cptm8-dev
type: Opaque
data:
    google-client-id: "b64id"
    google-client-secret: "b64secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-credentials
  namespace: cptm8-dev
type: Opaque
data:
    aws-access-key-id: "b64id"
    aws-secret-access-key: "b64key"